{
 "title": "Pizza Dashboard",
 "description": "Dashboard to show all jwt-pizza-service stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_ratio", "legendFormat": "__auto" },
    { "expr": "memory_usage_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successful/Unsuccessful Auths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(successful_auth_attempts_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(unsuccessful_auth_attempts_total[1m]) * 60",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Authenticated Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "authenticated_users_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" },
    { "expr": "http_requests_get_total", "legendFormat": "__auto" },
    { "expr": "http_requests_post_total", "legendFormat": "__auto" },
    { "expr": "http_requests_put_total", "legendFormat": "__auto" },
    { "expr": "http_requests_delete_total", "legendFormat": "__auto" }
   ]
  }
 ]
}